# Generated by Django 3.2 on 2021-09-01 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0002_comment_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
    ]
