# Generated by Django 3.2 on 2021-09-01 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0003_remove_comment_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='tags',
        ),
    ]
